### ISSUE TITLE
V D J gene name incompatibitlity with MiGEC output

### ISSUE THREAD

**Issue by drkoryjohns** [imminfo/tcr#10]
Hello,

Seems the genesegments.rda object does not contain the *01 suffix of the allele names that MiGEC reports in its output resulting in no results when running the geneUsage function.

Perhaps a regular expression line can be added to remove the *01 from the MiGEC reported alleles?

Thank you ... best,

Kory

**Comment by vadimnazarov** [comment]
Hello, 

I will soon add vectors with alleles so they could be used to compute the gene usage (allele usage?) without filtering the data. For removing "*01" and other allele indices I just added the `fix.alleles` function:

```
# your_data could be a data frame as well as a list of data frames
your_data <- fix.alleles(your_data)
```
