### ISSUE TITLE
Problem parsing immunoseq for tcR package -- Error: Error in scan(file = file, what = what, sep = sep, quote = quote, dec = dec,  :   scan() expected 'an integer', got 'nodata'

### ISSUE THREAD

**Issue by snedis** [imminfo/tcr#100]
I have problems to parse immunoseq data for the tcR package.
I read issue #74 and #83 and already applied to modification to parse.immunoseq3 as suggested to avoid the error message regarding the counts. I also updated all other headers which are different with the same principle.

I get the following error message>
Error in scan(file = file, what = what, sep = sep, quote = quote, dec = dec,  : 
  scan() expected 'an integer', got 'nodata'

The problem seems to be that I do not have integer values in the columns parse.cloneset expects them to have them. (E.g. I do not have a integer value for all n1_insertions. The original Immunoseq file has me  "no data" listed which I transformed into NA). 

I tried to modify parse.cloneset 
 swlist <- list ("character", "character", "integer", "integer", 
        "character", "character", "character", "character", "character", 
        "character", "character", "character", "character", "character")
 listing all these columns as "characters" and not "integer".

It still does not work. 

Can anyone help? Thank you!

**Comment by vadimnazarov** [comment]
Hi, tcR package is no longer supported and current issues will not be fixed. A new package is available that is designed to replace tcR called immunarch. We have solved most of the problems tcR package had and improved the overall pipeline, providing functions for painless repertoire file parsing and publication-ready plot making. 

The mission of the immunarch is to make immune repertoire data analysis as easy and possible—even with R. Please feel free to check it here: https://immunarch.com/

If you have any suggestions, bugs, improvements, etc. -- please write us or create an issue in https://github.com/immunomind/immunarch/issues

Thank you! Sincerely,
immunarch dev team and Vadim I. Nazarov, lead developer
