### ISSUE TITLE
parsing mixcr 3.0.3 file

### ISSUE THREAD

**Issue by ekelley903** [imminfo/tcr#101]
Hello,

It looks like the latest mixcr release, 3.0.3, is no longer parseable by tcR.  The clonotype counts were previously an integer, but are now a float and this is producing an error.

Error in scan(file = file, what = what, sep = sep, quote = quote, dec = dec,  : 
  scan() expected 'an integer', got '4347.0'

**Comment by tiagobrc** [comment]
Same problem here.
Do you have a solution?


Thanks.

**Comment by ekelley903** [comment]
I dropped the analysis w/ tcR at this point, because it looked to me like the package is no longer being supported.  You might try converting the float to an integer prior to parsing w/ tcR.

**Comment by tiagobrc** [comment]
Thanks for the help. It is a good short term solution. 

Thanks!

**Comment by vadimnazarov** [comment]
Hi, tcR package is no longer supported and current issues will not be fixed. A new package is available that is designed to replace tcR called immunarch. We have solved most of the problems tcR package had and improved the overall pipeline, providing functions for painless repertoire file parsing and publication-ready plot making. 

The mission of the new package “immunarch” is to make immune repertoire data analysis as easy and possible—even with R. Please feel free to check it here: https://immunarch.com/

If you have any suggestions, bugs, improvements, etc. -- please write us or create an issue in https://github.com/immunomind/immunarch/issues

Thank you! Sincerely,
immunarch dev team and Vadim I. Nazarov, lead developer
