### ISSUE TITLE
Error when trying to parse data

### ISSUE THREAD

**Issue by asc-2004** [imminfo/tcr#102]
In "https://mran.microsoft.com/snapshot/2015-02-27/web/packages/tcR/vignettes/tcrvignette.pdf" 
"In our analysis only few columns are broadly used. Hence, to do almost all analysis you just need a dataframes with following columns:-Read.count-CDR3.amino.acid.sequence-V.segmentsAdditionally, for analysis of J-segments usage or nucleotide sequences intersection (see Subsection3.1) you should provide:-J.segments-CDR3.nucleotide.sequence Any data frame with this columns is suitable for processing with the package..."

but I am getting this error (below) with a dataset containing: read.count, Percentage,CDR3.nucleotide.sequence,CDR3.amino.acid.sequence,V.segments,D.segments,J.segments

Error in `$<-.data.frame`(`*tmp*`, "Total.insertions", value = numeric(0)) : 
  replacement has 0 rows, data has 40

How to fix it?

**Comment by vadimnazarov** [comment]
Hi, tcR is no longer supporter. Please consider using http://immunarch.com that is a successor to the tcR package. Closing this for now.
