### ISSUE TITLE
unable to parse MiTCR outputs

### ISSUE THREAD

**Issue by joonlee3** [imminfo/tcr#16]
Hi,

  Currently, I am using MiTCR java application (v1.0.3) and tcR 2.1. I was attempting to parse MiTCR files by using the command "parse.mitcr" but I had trouble loading those MiTCR files. The error message that I've got is as follows:

> immdata1 <- parse.file("/Volumes/AdHoc_Analysis/Misc/TCR-Seq/MiTCR_results/tcR/ELM19.txt", 'mitcr')
> Error in `[.data.frame`(df, , make.names(.reads)) : 
>   undefined columns selected

The following is the first three lines from one of those MiTCR outputs

Read count      Percentage      CDR3 nucleotide sequence        CDR3 amino acid sequence        V segments      J segments      D segments      Last V nucleotide position      First D nucleotide position     Last D nucleotide position      First J nucleotide position     VD insertions   DJ insertions   Total insertions
1524    0.058755493869997684    TGTGCCAGCAGTCGCCCGGACTTTAGCTCCTATGAACAGTACTTC   CASSRPDFSSYEQYF TRBV26, TRBV24  TRBJ2-7 TRBD2   14      17      21      26      2       4       6
1297    0.050003855347366795    TGTGCCAGCTCTCTCGATTCAGGGGGACTGGGGGGGGCTAGTGCAGAAACGCTGTATTTT    CASSLDSGGLGGASAETLYF    TRBV12-2        TRBJ2-3 TRBD2   8       23      35      39      14      3       17

Would you please help me with this?

Thanks a lot!

Joon

**Comment by vadimnazarov** [comment]
Hello Joon, 

It's unexpected that MiTCR output do not have the first line with metadata. The MiTCR parser function tries to skip first line and then starts to read column names and rows. Have you removed somehow the very first line from the MiTCR output and then tried to parse it?

Anyway, you could use this function to parse MiTCR files without skipping the first line:
https://gist.github.com/vadimnazarov/1b438863748fdc3bccf1

**Comment by joonlee3** [comment]
First of all, thank you so much for your quick reply.

No. I ran MiTCR with one of the output format options '-level=2'.

It seems that the first line with metadata is added to the output when -level=3. Can these parse functions work with level 3 MiTCR outputs?

**Comment by vadimnazarov** [comment]
I just realised that this file structure could be due to the MiTCR run parameters. If you run MiTCR with `-level 3` parameter then `parse.mitcr` should work. I will try to fix this issue with the first line in the couple of days.

**Comment by vadimnazarov** [comment]
Yes!

**Comment by vadimnazarov** [comment]
I will post in this topic when I fix this issue to let you know about this update. Please let me know about any issues with `parse.mitcr` with `-level 3` and/or other bugs, I would greatly appreciate this.

**Comment by joonlee3** [comment]
It works well with level 3 data set. Thank you so much for your support.

**Comment by vadimnazarov** [comment]
Dear Joon,

I've just added the feature to parse different levels of MiTCR's output to the `parse.mitcr` function. If you would like to use it, please let me know if it works for you.

**Comment by joonlee3** [comment]
Thanks a lot. I'll try later and let you know. ^^

**Comment by juni-juli** [comment]
Dear Vadim,

I have the same problem as Joon, except that using level 3 output does not fix my problem:

 Error in `[.data.frame`(df, , make.names(c(.barcodes, .umi.prop, .reads,  : 
  undefined columns selected 

My first line contains metadata:

MiTCRFullExportV1.1 HomoSapiens TRB /media/sf_VMdata/mitcr/file1.fastq.gz   <parameters><format>1.0</format><exportedByVersion>1.0.3</exportedByVersion><gene>TRB</gene><species>HomoSapiens</species><qualityInterpretationStrategy><illumina>25</illumina></qualityInterpretationStrategy><cdr3Extractor><v><extensionDirections>both</extensionDirections><seedFrom>-4</seedFrom><seedTo>1</seedTo><minAlignmentMatches>12</minAlignmentMatches><lengthTolerance>3</lengthTolerance></v><j><extensionDirections>both</extensionDirections><seedFrom>-1</seedFrom><seedTo>4</seedTo><minAlignmentMatches>12</minAlignmentMatches><lengthTolerance>2</lengthTolerance></j><d><minLength>3</minLength><searchForRC /></d><upperCDR3LengthThreshold>100</upperCDR3LengthThreshold><lowerCDR3LengthThreshold>10</lowerCDR3LengthThreshold><strand>both</strand><includeCysPhe /></cdr3Extractor><cloneGenerator><segmentInformationAggregationFactor>0.15</segmentInformationAggregationFactor><maxErrorsInBadPoints>3</maxErrorsInBadPoints><proportionalMapping /></cloneGenerator><clusterizer><type>oneMismatch</type><maxClusterizationRatio>0.33</maxClusterizationRatio></clusterizer></parameters>  
Read count  Percentage  CDR3 nucleotide sequence    CDR3 nucleotide quality Min quality CDR3 amino acid sequence    V alleles   V segments  J alleles   J segments  D alleles   D segments  Last V nucleotide position  First D nucleotide position Last D nucleotide position  First J nucleotide position VD insertions   DJ insertions   Total insertions
5888    0.014855894293045634    TGTGCCAGCAGTGATTCGCGCGTCCAAGGGGCCAACGTCCTGACTTTC    HHHHHHHHGHHIHIIHIHGGGGGGGGHHGGGGGGHGGHHGGHHHHHHH    38  CASSDSRVQGANVLTF    TRBV6-1_01  TRBV6-1 TRBJ2-6_01  TRBJ2-6 TRBD1_01, TRBD2_02, TRBD2_01    TRBD1, TRBD2    13  21  24  27  7   2   9
4048    0.010213427326468873    TGTGCCAGCAACCCTGCGGGACAGTCAAAGGGACAGCAGTTCTTC   HHHHHHHHGHHHHGHHHHGGGGHGHHHHHHHGHGGGHHHHHHHHH   38  CASNPAGQSKGQQFF TRBV6-1_01  TRBV6-1 TRBJ2-1_01  TRBJ2-1 TRBD1_01    TRBD1   9   17  23  34  7   10  17

Do you have any idea what might cause this?
Thanks in advance!

**Comment by vadimnazarov** [comment]
Hi!

Could you please update to the latest development version via

```
install.packages("devtools")
devtools::install_github("imminfo/tcR", build_vignettes = FALSE, ref = "develop")
```

and try to parse files again?

**Comment by juni-juli** [comment]
Hi, thanks for the quick response!
 The installation failed with this message:

> library(devtools)
> devtools::install_github("imminfo/tcR", build_vignettes = FALSE, ref = "develop")
> Downloading github repo imminfo/tcR@develop
> Installing tcR
> "C:/PROGRA~1/R/R-32~1.1/bin/x64/R" --no-site-file --no-environ --no-save --no-restore CMD INSTALL  \
>   "C:/Users/WSUser/AppData/Local/Temp/RtmpS4Ig9x/devtools1e445fbb3a1a/imminfo-tcr-3a98516"  \
>   --library="C:/Users/WSUser/Documents/R/win-library/3.2" --install-tests 
- installing _source_ package 'tcR' ...
  *\* libs

**\* arch - i386
Warnung: Ausführung von Kommando 'make -f "Makevars" -f "C:/PROGRA~1/R/R-32~1.1/etc/i386/Makeconf" -f "C:/PROGRA~1/R/R-32~1.1/share/make/winshlib.mk" CXX='$(CXX1X) $(CXX1XSTD)' CXXFLAGS='$(CXX1XFLAGS)' CXXPICFLAGS='$(CXX1XPICFLAGS)' SHLIB_LDFLAGS='$(SHLIB_CXX1XLDFLAGS)' SHLIB_LD='$(SHLIB_CXX1XLD)' SHLIB="tcR.dll" OBJECTS="RcppExports.o neighbour.search.o"' ergab Status 127
ERROR: compilation failed for package 'tcR'
- removing 'C:/Users/WSUser/Documents/R/win-library/3.2/tcR'
- restoring previous 'C:/Users/WSUser/Documents/R/win-library/3.2/tcR'
  Error: Command failed (1)
  >

**Comment by vadimnazarov** [comment]
Hi,

could you please install Rtools (http://cran.r-project.org/bin/windows/Rtools/) for Windows, that is needed to build packages?
