### ISSUE TITLE
How to update to the latest version?

### ISSUE THREAD

**Issue by vixenk** [imminfo/tcr#2]
> devtools::install_github("imminfo/tcr", build_vignettes = FALSE)

Downloading github repo imminfo/tcr@master
Installing tcR
'/Library/Frameworks/R.framework/Resources/bin/R' --vanilla CMD INSTALL  \
  '/private/var/folders/w7/b1cyd7nn5p1_kc6b9kgz8n5w0000gn/T/RtmpZYK2Vn/devtools523538bc4d15/imminfo-tcr-624ead0'  \
  --library='/Library/Frameworks/R.framework/Versions/3.1/Resources/library' --install-tests 
- installing _source_ package ‘tcR’ ...
  Error : Invalid DESCRIPTION file

Malformed package version.

See the information on DESCRIPTION files in section 'Creating R
packages' of the 'Writing R Extensions' manual.

ERROR: installing package DESCRIPTION failed for package ‘tcR’
- removing ‘/Library/Frameworks/R.framework/Versions/3.1/Resources/library/tcR’
- restoring previous ‘/Library/Frameworks/R.framework/Versions/3.1/Resources/library/tcR’
  Error: Command failed (1)

**Comment by vadimnazarov** [comment]
Fixed, thank you.
