### ISSUE TITLE
diversity() function warning message

### ISSUE THREAD

**Issue by vixenk** [imminfo/tcr#20]
Umi.proportion column does sum in 1, I've checked, but

> diversity(a[[1]]$Umi.proportion, .q = 1)
> Warning! Sum of the input vector is NOT equal to 1. Function may produce incorrect results.
> To fix this try to set .do.norm = TRUE in the function's parameters.
> [1] 152946.6
> diversity(a[[1]]$Umi.proportion, .q = 1, .do.norm = T)
> Warning! Sum of the input vector is NOT equal to 1. Function may produce incorrect results.
> To fix this try to set .do.norm = TRUE in the function's parameters.

**Comment by vadimnazarov** [comment]
R have problems with floating point numbers sometimes. I will add warning about that, thanks!
