### ISSUE TITLE
Incorrect index calculations in shared.repertoire()

### ISSUE THREAD

**Issue by vixenk** [imminfo/tcr#21]
Hi Vadim, 
when trying to get an shared rep-r with Index numbers

> sh111 = shared.repertoire(ash111, .type = 'avi', .min.ppl = 1, .clear = T, .verbose = T)

something went wrong, because I see a lot of same(!) indices in columns, e.g. (data.frame ordered by col i111-0):
![image](https://cloud.githubusercontent.com/assets/6222751/8375237/26133f76-1c04-11e5-855d-6146dfa9bfcc.png)

But when using .sum.col='Index' all works fine.

**Comment by vadimnazarov** [comment]
Fixed.
