### ISSUE TITLE
Regarding count.frame

### ISSUE THREAD

**Issue by joonlee3** [imminfo/tcr#22]
Hi,

  When I use a function 'count.frames', should the sum of # of in-frame and out-of-frame sequences be equal to # of all sequences? For example, from my analysis, I found out that

> count.frames(tcr_mm[[1]], 'all')  
> [1] 1223
> count.frames(tcr_mm[[1]], 'in')  
> [1] 1166
> count.frames(tcr_mm[[1]], 'out')  
> [1] 52

  I thought that 
     count.frames(tcr_mm[[1]], 'out') + count.frames(tcr_mm[[1]], 'in') = count.frames(tcr_mm[[1]], 'all')

  Did I miss something? Please let me know.

Thanks,
Joon

**Comment by vadimnazarov** [comment]
Hi Joon,

there is a parameter `.coding` that could affect the results. By default it's TRUE that means that only coding sequences (i.e., without stop-codon) will be returned as a result. You may take a look at the help page `?count.frames` to see this parameter.
