### ISSUE TITLE
js.div.seg

### ISSUE THREAD

**Issue by PenguinNell** [imminfo/tcr#3]
Если остальные параметры в js.div.seg - это параметры freq.Vb, то там не хватает .laplace.
Не разобралась с Labels..

**Comment by vadimnazarov** [comment]
Почему, там есть параметр .laplace же, он там в самом конце. А что такое Labels?

**Comment by PenguinNell** [comment]
В пакете на винде нету =(
Labels: "если появляется не баг, а что-то хочется добавить или изменить, то тоже создаем issue. Из labels выбираем “enchancement”

**Comment by vadimnazarov** [comment]
А у тебя точно 1.4 версия пакета? Попробуй с гитхаба установить через devtools.

**Comment by PenguinNell** [comment]
Обновила, теперь всё есть =)
