### ISSUE TITLE
Monkey TCR support

### ISSUE THREAD

**Issue by charlesliu1975** [imminfo/tcr#34]
Does tcR support monkey TCR？ I found segments.alphabets support human and mouse only. Could you please add monkey TCR. There are 59 TRBV and 13 TRBJ genes of monkey in IMGT.

Can I analyse the IMGT results?

Thank you.

**Comment by vadimnazarov** [comment]
```
Does tcR support monkey TCR？ I found segments.alphabets support human and mouse only. 
Could you please add monkey TCR. There are 59 TRBV and 13 TRBJ genes of monkey in IMGT.
```

Hi, sure, done. You need to update to the latest development version from GitHub. Name of gene alphabets - MACMUL_TRBV and MACMUL_TRBJ

```
# install.packages("devtools")
devtools::install_github("imminfo/tcr", build_vignettes = FALSE)
```

Please let me know if it works (or not) for you.

   Can I analyse the IMGT results?

I'm sorry, but no, you can't analyse the IMGT results with the package. I highly recommend you to use [MiXCR](http://mixcr.milaboratory.com) or [MiGEC](http://milaboratory.com/projects/migec-project/). It's been shown that MiXCR and MiGEC allows more precise and faster identification of TCR / Ig gene segments. For those tools I have a parsers of their outputs in the package.

**Comment by vadimnazarov** [comment]
Added rhesus monkey alphabets.
