### ISSUE TITLE
cloneset.stats(twb)

### ISSUE THREAD

**Issue by pramod27** [imminfo/tcr#37]
Hi Nazarov,
Hi,

Thanks for the  examples online: https://imminfo.github.io/tcr/

however when I am executing

> cloneset.stats(twb)

I am getting the following error:
Error in get.outframes(.data, .head, .coding) : unused argument (.coding)

Could you please help me to fix it?

Thanks,
Pramod

**Comment by vadimnazarov** [comment]
Hi Pramod,
I answered to you via e-mail.

I will close this issue when the bug will be fixed.

**Comment by pramod27** [comment]
sounds good.
Thanks,
Pramos]d

**Comment by vadimnazarov** [comment]
Fixed.
