### ISSUE TITLE
shared(overlap, findclonotype - whatever) - need more columns

### ISSUE THREAD

**Issue by iziziz** [imminfo/tcr#4]
Why don't allow getting more informative columns when using function shared.. ? For example: if i need to get the set like 'Rank', 'Barcode.count', 'Percentage' for shared clonotypes...

?

**Comment by vadimnazarov** [comment]
What is the difference between this modification of `shared.repertoire` and `find.clonotypes` then?

A few functions depend on the current structure of the output of `shared.repertoire`, so it would be quite complicated to redesign all of this.

**Comment by iziziz** [comment]
mmm... seems, you're right - there will be no difference. The problem is absence of useful function for getting info both about presence of particular clonotype in several repertoires and it's (the clonotype) features not only CDR3.nuc.seq and V.seg. So, it's all about "tracking.function". )
