### ISSUE TITLE
Error parsing MiXCR file

### ISSUE THREAD

**Issue by peterch405** [imminfo/tcr#42]
The command `parse.mixcr("<path to mixcr.txt>")`

produces the following error:

`Error in FUN(X[[i]], ...) : subscript out of bounds`

Converting the file into vdjtools format and importing using `parse.vdjtools` works. 

Using tcR version 2.2.1

**Comment by vadimnazarov** [comment]
Hi, 

could you please send to my e-mail vdm dot nazarov at gmail com (see the package DESCRIPTION file for it) the very first 5 lines of this MiXCR file? I'll find the possible bugs and update the package.

**Comment by vadimnazarov** [comment]
It seems that this is a bug in MiXCR output.

**Comment by fabio-t** [comment]
Hi @vadimnazarov, I'm having the same problem. Can you please expand as to what problem there is on MiXCR output, so that I can open an issue there and get it solved?

**Comment by vadimnazarov** [comment]
Hi @fabioticconi , do you have the latest version of the MiXCR software? if not, than please update it and try again, I think they fixed this bug in the latest versions. If you have the latest one or if the update isn't working , then please send me (via e-mail) the very first 5-10 lines of the file, so I can run it on my pc and fix the bug in tcR which causes parsing to fail.

**Comment by fabio-t** [comment]
Hi, yes I use the latest version of mixcr. I've just sent a file for your tests.

**Comment by vadimnazarov** [comment]
It was a bug in MiXCR
