### ISSUE TITLE
js.div.seg is not using .quant !

### ISSUE THREAD

**Issue by iziziz** [imminfo/tcr#43]
I've got pretty same numbers with .quant=NA and .quant='umi.count'

the problem in here:

"
js.div.seg
function (.data, .genes = HUMAN_TRBV, .frame = c("all", "in", 
    "out"), .quant = c(NA, "read.count", "umi.count", "read.prop", 
    "umi.prop"), .norm.entropy = T, .ambig = F, .verbose = F, 
    .data2 = NULL) 
...
if (has.class(.genes, "list") && length(.genes) == 2) {
        freq.alpha <- geneUsage(.data, .genes = .genes, .ambig = .ambig)
        freq.beta <- geneUsage(.data2, .genes = .genes, .ambig = .ambig)
    }
...
"

ver 2.1.1

IZ

**Comment by vadimnazarov** [comment]
Done, update is on the develop branch
