### ISSUE TITLE
geneUsage error if .norm=T

### ISSUE THREAD

**Issue by iziziz** [imminfo/tcr#44]
> x=geneUsage(d0.new.data[[1]], .norm = T)
> Error in apply(res[, -1], 2, function(col) col/sum(col)) : 
>   dim(X) must have a positive length
> 
> str(d0.new.data[[1]])
> 'data.frame':   270080 obs. of  16 variables:
>  $ Umi.count               : int  8086 6312 4731 4401 3745 3542 3534 3506 3010 2693 ...
>  $ Umi.proportion          : num  0.01376 0.01074 0.00805 0.00749 0.00637 ...
>  $ Read.count              : int  8086 6312 4731 4401 3745 3542 3534 3506 3010 2693 ...
>  $ Read.proportion         : num  0.01376 0.01074 0.00805 0.00749 0.00637 ...
>  $ CDR3.nucleotide.sequence: chr  "TGCGCCAGCAGCCAAGATACCGGGATGAAATTAAGCTCCTACAATGAGCAGTTCTTC" "TGTGCCAGCAGTGAAAGACCGCCTAAACCTCAAAACATTCAGTACTTC" "TGCAGCGTTGATGTGGTACAATACACTAGCACAGATACGCAGTATTTT" "TGTGCCAGCAGCTTCCTATCTAGCTCCTACGAGCAGTACTTC" ...
>  $ CDR3.amino.acid.sequence: chr  "CASSQDTGMKLSSYNEQFF" "CASSERPPKPQNIQYF" "CSVDVVQYTSTDTQYF" "CASSFLSSSYEQYF" ...
>  $ V.gene                  : chr  "TRBV4-3" "TRBV6-1" "TRBV29-1" "TRBV12-4, TRBV12-3" ...
>  $ J.gene                  : chr  "TRBJ2-1" "TRBJ2-4" "TRBJ2-3" "TRBJ2-7" ...
>  $ D.gene                  : chr  "TRBD2" "TRBD2" "TRBD1, TRBD2" "TRBD2" ...
>  $ V.end                   : int  16 14 10 10 14 14 11 15 15 15 ...
>  $ J.start                 : int  35 31 27 23 30 32 22 25 29 34 ...
>  $ D5.end                  : int  20 27 22 19 15 20 13 22 18 22 ...
>  $ D3.end                  : int  24 30 24 22 27 26 16 24 26 28 ...
>  $ VD.insertions           : int  3 12 11 8 0 5 1 6 2 6 ...
>  $ DJ.insertions           : int  10 0 2 0 2 5 5 0 2 5 ...
>  $ Total.insertions        : int  13 12 13 8 2 10 6 6 4 11 ...

IZ

**Comment by vadimnazarov** [comment]
Done, update from the develop branch
