### ISSUE TITLE
Include MOUSE_TRAV and MOUSE_TRAJ in segments.alphabets within tcR

### ISSUE THREAD

**Issue by stevedaley** [imminfo/tcr#45]
Some labs study T-cell development using high-throughput sequencing of TCR alpha chains in TCR-beta chain transgenic mice. To be more useful to these labs, alphabets for mouse alpha chains, i.e. MOUSE_TRAV and MOUSE_TRAJ, could be included in segments.alphabets within tcR.

**Comment by vadimnazarov** [comment]
Hi, ok, I'm not able to do this in the nearest week, but you could change necessary files (docdata.R) if you would like to speed up the process and create a pull request which I will accept.

**Comment by vadimnazarov** [comment]
Done, update to the latest stable development version in order to use them
