### ISSUE TITLE
parse.cloneset

### ISSUE THREAD

**Issue by vixenk** [imminfo/tcr#46]
Привет, а вот такой вопрос: 
если я хочу распарсить клонсет .txt, но там другие названия колонок и структура тоже другая, то я использую parse.cloneset, где я могу вручную сопоставить названия колонок в файле и в tcR. Но, если у меня нет колонок, например v.end, то он выдает эррор:

Error in .make.names(.vend) : 
argument ".vend" is missing, with no default

А если вручную везде прописать NA, то:

b = parse.cloneset(.filename = '/media/RAID/users/KK/mitcr/Luk/chu/10months.txt', .aa.seq = 'AA.Sequence', .reads = 'Seq.Count', .vgenes = 'V.segments', .nuc.seq = 'N.Sequence', .jgenes = 'J.segments', .skip = 1, .sep = '\t' , .barcodes = NA, .dgenes = NA, .vend = NA, .jstart = NA, .dalignments = NA,.vd.insertions = NA,.dj.insertions = NA,.total.insertions = NA)
Error in `[.data.frame`(df, , make.names(.reads)) : 
undefined columns selected

**Comment by vadimnazarov** [comment]
Ты зря пишешь .skip = 1, это означает, что надо пропустить первую строку, а потом уже начинать парсить названия колонок. Тебе нужен .skip = 0.
Внимательно проверь названия колонок, по-моему, у тебя лишние точки в названиях, тебе нужно указывать точное название колонки из файла (с пробелами, прям как есть)
Я исправил, можешь обновиться до develop ветки

**Comment by vadimnazarov** [comment]
У тебя получилось? Я бы тогда закрыл issue.

**Comment by vixenk** [comment]
Обновилась, не получается. в файле названия колонок верны, все совпадает. Skip не меняет дела(
Error тот же.

**Comment by vadimnazarov** [comment]
Это странно, я загрузил твой файл, и у меня все получилось. Напиши, какой командой ты это делаешь, пожалуйста
