### ISSUE TITLE
function chao1 - what if no singletons but duplicates

### ISSUE THREAD

**Issue by kvanhoorde** [imminfo/tcr#51]
The current function seems to result in errors when there are no singletons but duplicates. It runs the third part of the code (i.e. else) but the value for f1 is NA since this is the value of counts for '1'. Also it seems that this option is not really covered by the comment lines. Three options are considered: no singletons and no duplicates, singletons but no duplicates, singletons and duplicates. But what if no singletons but duplicates?

**Comment by vadimnazarov** [comment]
It seems that in this case there should be an error message because chao1 is not suitable for diversity estimation in this case. Do you have any other suggestions on how to deal with it?

**Comment by vadimnazarov** [comment]
Hi, tcR package is no longer supported and current issues will not be fixed. A new package is available that is designed to replace tcR called immunarch. We have solved most of the problems tcR package had and improved the overall pipeline, providing functions for painless repertoire file parsing and publication-ready plot making. 

The mission of the immunarch is to make immune repertoire data analysis as easy and possible—even with R. Please feel free to check it here: https://immunarch.com/

If you have any suggestions, bugs, improvements, etc. -- please write us or create an issue in https://github.com/immunomind/immunarch/issues

Thank you! Sincerely,
immunarch dev team and Vadim I. Nazarov, lead developer
