### ISSUE TITLE
function vis.heatmap - additional parameters

### ISSUE THREAD

**Issue by kvanhoorde** [imminfo/tcr#52]
Is it maybe possible to add an additional parameter which allows to request a scientific notation in the heatmap? Since otherwise there might be a lot of digits in the plot, making the plot unclear.
(If desired I can pull and push changes since I modified the function for myself.)

**Comment by vadimnazarov** [comment]
Added, thanks!

**Comment by kvanhoorde** [comment]
Thanks for your modifications. However it seems to me that in this way the scientific notation is not used since the modification to m is done after supplying m already to ggplot.
