### ISSUE TITLE
function vis.kmer.histogram - additional parameter

### ISSUE THREAD

**Issue by kvanhoorde** [imminfo/tcr#53]
When using the vis.kmer.histogram function, It would be interesting to have the x-axis sorted on decreasing frequency instead of alphabetically. Maybe it is an option to include an additional parameter where you can specify whether you would like to have the plot showing decreasing frequency or how you want to sort the x-axis?
(If desired I can pull and push changes since I modified the function for myself.)

**Comment by vadimnazarov** [comment]
Hi, sure, feel free to issue a pull request for each issue. It will greatly increase a speed of adding new features you would like to see. If something won't work on my machine, I will let you know in a thread corresponding to this pull request. And please start a separate pull request for each issue, so I can check them one after another.

**Comment by vadimnazarov** [comment]
Hi, tcR package is no longer supported and current issues will not be fixed. A new package is available that is designed to replace tcR called immunarch. We have solved most of the problems tcR package had and improved the overall pipeline, providing functions for painless repertoire file parsing and publication-ready plot making. 

The mission of the immunarch is to make immune repertoire data analysis as easy and possible—even with R. Please feel free to check it here: https://immunarch.com/

If you have any suggestions, bugs, improvements, etc. -- please write us or create an issue in https://github.com/immunomind/immunarch/issues

Thank you! Sincerely,
immunarch dev team and Vadim I. Nazarov, lead developer
