### ISSUE TITLE
Unable to parse.vdjtools due to Error

### ISSUE THREAD

**Issue by MoentyPython** [imminfo/tcr#66]
Hey,

I am trying to analyse data from IMGT, VDJtools allows conversion of IMGT data into the VDJ-format, which in turn I would like to read into R to analyse with tcR. When I run `parse.vdjtools("filename.txt")` it returns following Error:

```
Error in `[.data.frame`(df, , make.names(.reads)) : 
  undefined columns selected
```

So does that mean that the file that VDJtools created from my IMGT input cannot be read/parsed via tcR, or is it a different setting or step I have missed? I have attached a sample file that has the same format .

[VDJSF6.3_Nt-sequences.txt](https://github.com/imminfo/tcr/files/106777/VDJSF6.3_Nt-sequences.txt)

I saw a same error with MiTCR but that answer there was not helpful for the same issue with VDJtools

**Comment by vadimnazarov** [comment]
Hi,

could you tell me please what version of tcR package do you use?

**Comment by vadimnazarov** [comment]
Please update to the latest development version (see the website on how to do that) of the package and try again.

**Comment by MoentyPython** [comment]
Thank you for the really quick answer! I was on the latest stable version 2.2.1.7, I updated to 2.2.1.8 unstable dev. version and it works now. However, in RStudio the package version is still listed as 2.2.1.7, dont know why.

Thank you for your help!

**Comment by MoentyPython** [comment]
If I could ask one more question: I am trying to combine my data of different samples/subjects into one list similar to the twb sample data. I want this so when I plot different graphs it will plot each of my samples in one graph/plot. I am not able to use, for example, `vis.top.proportions(data1, data2)` as I get following error: `Error: length(n) == 1L is not TRUE`. I am assuming because each file has a different number of sequences?

What do you recommend for analysis and comparision for several samples?

**Comment by vadimnazarov** [comment]
Hi, good to hear that!

Sure. Take a look at a manual to `vis.top.proportions` - it's input is only one list. So if your data1 and data2 are two lists, you need to combine them to get one big plot, or call the function separately for each input list. Is it helpful for you or did I misunderstand you?

**Comment by MoentyPython** [comment]
Yes, thank you that helped! All I had to do was use `list(data1, data2)` to get a file similar to the twb structure! 

Thank you for your great support and please continue the great work :+1:

**Comment by vadimnazarov** [comment]
Thank you for your kind words!
