### ISSUE TITLE
VJ combination geneUsage result missed the last V and J segments

### ISSUE THREAD

**Issue by vixenk** [imminfo/tcr#73]
When using geneUsage with .genes = list(HUMAN_TRBV_MITCR, HUMAN_TRBJ) either on a single df or on list with df's
`geneUsage(datalist[[1]], .genes = list(HUMAN_TRBV_MITCR, HUMAN_TRBJ), .quant = NA, .norm = T, .ambig = F)`
, it results in a 47x12 tables, missing TRBV9 row and TRBJ2-7 column.

I use the very last version of Master branch.

**Comment by vadimnazarov** [comment]
Fixed, please check it

**Comment by vixenk** [comment]
Yep, seems to work correct.

**Comment by vadimnazarov** [comment]
nice!
