### ISSUE TITLE
Bug when parsing immunoseq Error in `[.data.frame`(df, , make.names(.reads)) : undefined columns selected

### ISSUE THREAD

**Issue by nachocab** [imminfo/tcr#74]
Hi, thanks for sharing your package!

I found an error when parsing Immunoseq files. The header doesn't match my files, so I had to fix it by changing:

```
reads <- 'count (reads)'
```

into

```
reads <- 'count (templates/reads)'
```

I'd suggest combining all 3 immunoseq parsers and allow passing a custom header as an argument.

**Comment by vadimnazarov** [comment]
Hi, tcR package is no longer supported and current issues will not be fixed. A new package is available that is designed to replace tcR called immunarch. We have solved most of the problems tcR package had and improved the overall pipeline, providing functions for painless repertoire file parsing and publication-ready plot making. 

The mission of the immunarch is to make immune repertoire data analysis as easy and possible—even with R. Please feel free to check it here: https://immunarch.com/

If you have any suggestions, bugs, improvements, etc. -- please write us or create an issue in https://github.com/immunomind/immunarch/issues

Thank you! Sincerely,
immunarch dev team and Vadim I. Nazarov, lead developer
