### ISSUE TITLE
New input formats

### ISSUE THREAD

**Issue by vadimnazarov** [imminfo/tcr#8]
Please specify here which software for processing NGS data and extracting CDR3 sequences do you use so I can update _tcR_ with function for reading the output of this software.

**Comment by this-is-how-we-see** [comment]
[sampleExport.2017-01-16_10-03-10.zip](https://github.com/imminfo/tcr/files/709114/sampleExport.2017-01-16_10-03-10.zip)

I have been parsing Adaptive immunoSEQ files and am really enjoying the additional functionality available in tcR. 

I have found that files that I had sequenced more recently will not parse as .format = "immunoseq3". Can you look at the file and determine if immunoseq4 needs to be arranged for the updated .col headings? I am not a programmer or I would offer to assist.

Thank you for creating this amazing package!
