### ISSUE TITLE
Issue with name fixes

### ISSUE THREAD

**Issue by wyattmcdonnell** [imminfo/tcr#81]
V/D/J segment name fixes for immunoSEQ parsers won't work correctly even if the parsers were working. Example: V20-1 is left as V20-1 even though tcR uses V20 for gene usage analysis.

**Comment by vadimnazarov** [comment]
Hi, tcR package is no longer supported and current issues will not be fixed. A new package is available that is designed to replace tcR called immunarch. We have solved most of the problems tcR package had and improved the overall pipeline, providing functions for painless repertoire file parsing and publication-ready plot making. 

The mission of the immunarch is to make immune repertoire data analysis as easy and possible—even with R. Please feel free to check it here: https://immunarch.com/

If you have any suggestions, bugs, improvements, etc. -- please write us or create an issue in https://github.com/immunomind/immunarch/issues

Thank you! Sincerely,
immunarch dev team and Vadim I. Nazarov, lead developer
