### ISSUE TITLE
New immunoSEQ files won't parse. 

### ISSUE THREAD

**Issue by this-is-how-we-see** [imminfo/tcr#83]
I'm trying to parse a few hundred immunoSEQ files and I don't think it's ID'ing the columns. Could their be a new format that is not compatible?

**Comment by ccasar** [comment]
I ran into the same issue with current immunoSEQ files, as suggested in issue https://github.com/imminfo/tcr/issues/74 the file headers aren't parsed correctly.

In my case, I changed the column name "count (templates/reads)" to "count (reads)" and parsing with .format = 'immunoseqv3' worked again. Depending on what format you are using you might need to change other column names. Have a look at the parse.immunseqX functions in https://github.com/imminfo/tcr/blob/master/R/parsing.R#L523 to get a grasp on it.

**Comment by this-is-how-we-see** [comment]
Thanks! That worked. I was afraid there would be other issues and I have 400+ files to parse and analyze.

**Comment by EdGreen21** [comment]
For those of us experienced in coding but new to R (like me!): 

load tcR library, then edit the parser code by running the following line:

trace("parse.immunoseq3",edit=TRUE)

Then make the edit suggested in issue #74 as described by ccasar

**Comment by vadimnazarov** [comment]
Hi, tcR package is no longer supported and current issues will not be fixed. A new package is available that is designed to replace tcR called immunarch. We have solved most of the problems tcR package had and improved the overall pipeline, providing functions for painless repertoire file parsing and publication-ready plot making. 

The mission of the immunarch is to make immune repertoire data analysis as easy and possible—even with R. Please feel free to check it here: https://immunarch.com/

If you have any suggestions, bugs, improvements, etc. -- please write us or create an issue in https://github.com/immunomind/immunarch/issues

Thank you! Sincerely,
immunarch dev team and Vadim I. Nazarov, lead developer
