### ISSUE TITLE
Differential abundance calculation? 

### ISSUE THREAD

**Issue by awalsh17** [imminfo/tcr#87]
Do you have plans to add a test to identify sequences that are differentially abundant between two samples? Such as for expansion of clones after some stimulation or other intervention?
There is a method developed by Adaptive team:
J. Virol. April 2015 vol. 89 no. 8 4517-4526 
That calculates p-value and adjusts for multiple hypotheses. I have written an R function, but it is slow... maybe you want to use it and see if you can speed it up?

**Comment by vadimnazarov** [comment]
Hi, tcR package is no longer supported and current issues will not be fixed. A new package is available that is designed to replace tcR called immunarch. We have solved most of the problems tcR package had and improved the overall pipeline, providing functions for painless repertoire file parsing and publication-ready plot making. 

The mission of the immunarch is to make immune repertoire data analysis as easy and possible—even with R. Please feel free to check it here: https://immunarch.com/

If you have any suggestions, bugs, improvements, etc. -- please write us or create an issue in https://github.com/immunomind/immunarch/issues

Thank you! Sincerely,
immunarch dev team and Vadim I. Nazarov, lead developer
