### ISSUE TITLE
Skipping files while parsing

### ISSUE THREAD

**Issue by anabbi** [imminfo/tcr#88]
Hello

I am trying to parse many mixcr files using tcR package but along the way I get this error:

Error in `$<-.data.frame`(`*tmp*`, "VD.insertions", value = -1) : 
  replacement has 1 row, data has 0

I guess some of my files do not have VD insertions. Is there an arg I can pass to continue parsing if it finds a file with no VD insertions?

Thanks

**Comment by vadimnazarov** [comment]
Hi, tcR package is no longer supported and current issues will not be fixed. A new package is available that is designed to replace tcR called immunarch. We have solved most of the problems tcR package had and improved the overall pipeline, providing functions for painless repertoire file parsing and publication-ready plot making. 

The mission of the immunarch is to make immune repertoire data analysis as easy and possible—even with R. Please feel free to check it here: https://immunarch.com/

If you have any suggestions, bugs, improvements, etc. -- please write us or create an issue in https://github.com/immunomind/immunarch/issues

Thank you! Sincerely,
immunarch dev team and Vadim I. Nazarov, lead developer
