### ISSUE TITLE
signif.digits in vis.heatmap does not work as espected

### ISSUE THREAD

**Issue by tiagobrc** [imminfo/tcr#90]
Using the value of 1 results in 5 decimal digits, using 0 results in 1. 

```
vis.heatmap(twb.shared, .title = "morisita index", 
            .labs = c("Sample in x", "Sample in y"), .legend = "# index",.size.text = 2 ,.signif.digits = 1)
![rplot01](https://user-images.githubusercontent.com/12516337/32913046-47b3bb06-caf8-11e7-8683-37254449d760.png)

```

**Comment by vadimnazarov** [comment]
Hi, tcR package is no longer supported and current issues will not be fixed. A new package is available that is designed to replace tcR called immunarch. We have solved most of the problems tcR package had and improved the overall pipeline, providing functions for painless repertoire file parsing and publication-ready plot making. 

The mission of the immunarch is to make immune repertoire data analysis as easy and possible—even with R. Please feel free to check it here: https://immunarch.com/

If you have any suggestions, bugs, improvements, etc. -- please write us or create an issue in https://github.com/immunomind/immunarch/issues

Thank you! Sincerely,
immunarch dev team and Vadim I. Nazarov, lead developer
