### ISSUE TITLE
importing mixcr dataset

### ISSUE THREAD

**Issue by lilycanfly** [imminfo/tcr#91]
Hi,

I try to import the example dataset download (MZTwins) from http://labcfg.ibch.ru/tcr.html. It showns the following error. Could someone help me?

Thanks.

![image](https://user-images.githubusercontent.com/32545217/34504076-1de23390-efea-11e7-87fb-4761d419fceb.png)

**Comment by vadimnazarov** [comment]
Hi, tcR package is no longer supported and current issues will not be fixed. A new package is available that is designed to replace tcR called immunarch. We have solved most of the problems tcR package had and improved the overall pipeline, providing functions for painless repertoire file parsing and publication-ready plot making. 

The mission of the immunarch is to make immune repertoire data analysis as easy and possible—even with R. Please feel free to check it here: https://immunarch.com/

If you have any suggestions, bugs, improvements, etc. -- please write us or create an issue in https://github.com/immunomind/immunarch/issues

Thank you! Sincerely,
immunarch dev team and Vadim I. Nazarov, lead developer
