### ISSUE TITLE
Names of gene segments in tcR

### ISSUE THREAD

**Issue by shigekinakagome** [imminfo/tcr#93]
Hi,
we found inconsistent annotation of gene names between MiXCR outputs and tcR. For example, one segment in the V region is named as "TRAV38-2DV8" in our MiXCR output. We counted the number of clonotypes incuding this segment and it was around 9300. However, this segment was not recognized in the vis.gene.usage function, and the number was zero. This could be because this gene is annotated as "TRAV38-2/DV8" in the vis.gene.usage function. A similar issue happened to the gene "TRAV36DV7" (counted as 2500 in our MiXCR output), which is annotated as "TRAV36/DV7" in the vis.gene.usage function. Would there be any solution for this issue? Thank you.

**Comment by vadimnazarov** [comment]
Hi, tcR package is no longer supported and current issues will not be fixed. A new package is available that is designed to replace tcR called immunarch. We have solved most of the problems tcR package had and improved the overall pipeline, providing functions for painless repertoire file parsing and publication-ready plot making. 

The mission of the immunarch is to make immune repertoire data analysis as easy and possible—even with R. Please feel free to check it here: https://immunarch.com/

If you have any suggestions, bugs, improvements, etc. -- please write us or create an issue in https://github.com/immunomind/immunarch/issues

Thank you! Sincerely,
immunarch dev team and Vadim I. Nazarov, lead developer
