### ISSUE TITLE
vis.rarefaction Warning: Ignoring unknown aesthetics: Group

### ISSUE THREAD

**Issue by gavin-kelly-1** [imminfo/tcr#94]
https://github.com/imminfo/tcr/blob/96c36080237f3c3087147dbcd37223414fcc506e/R/plots.R#L603

Think there's a typo, _group_ rather than _Group_ as an aesthetic.  But changing that means that each group contains two linetypes, so I got it to work by grouping by Type within People
`...,group=interaction(People, Type),...`
Thanks for the package - really helping me understand what questions TCR data is capable of answering.

**Comment by vadimnazarov** [comment]
Hi, tcR package is no longer supported and current issues will not be fixed. A new package is available that is designed to replace tcR called immunarch. We have solved most of the problems tcR package had and improved the overall pipeline, providing functions for painless repertoire file parsing and publication-ready plot making. 

The mission of the immunarch is to make immune repertoire data analysis as easy and possible—even with R. Please feel free to check it here: https://immunarch.com/

If you have any suggestions, bugs, improvements, etc. -- please write us or create an issue in https://github.com/immunomind/immunarch/issues

Thank you! Sincerely,
immunarch dev team and Vadim I. Nazarov, lead developer
