### ISSUE TITLE
Sample names in mixcr input 

### ISSUE THREAD

**Issue by cartal** [imminfo/tcr#96]
Hi, 

I'm using parse.folder as follows:

MT <- parse.folder('.', 'mixcr')

Everything works fine, but the sample name is lost somehow and I can't really assign names in the plots. I have tried supplying a vector with the .namelist option, but doesn't work either. 

Any ideas on how to solve it? 

Thank you!

**Comment by vadimnazarov** [comment]
Hi, tcR package is no longer supported and current issues will not be fixed. A new package is available that is designed to replace tcR called immunarch. We have solved most of the problems tcR package had and improved the overall pipeline, providing functions for painless repertoire file parsing and publication-ready plot making. 

The mission of the immunarch is to make immune repertoire data analysis as easy and possible—even with R. Please feel free to check it here: https://immunarch.com/

If you have any suggestions, bugs, improvements, etc. -- please write us or create an issue in https://github.com/immunomind/immunarch/issues

Thank you! Sincerely,
immunarch dev team and Vadim I. Nazarov, lead developer
